"""
Association Tree Generator — The Creative Core.

Generates a branching tree of lateral associations from a seed topic,
pruning at each level to keep only the most promising branches.
Each hop is generated by the LLM and aims to cross domain boundaries.

When embeddings are available, every node gets a semantic vector and
pruning uses real cosine distance from the seed — rewarding chains
that fly the farthest in concept space, not just crossing domain labels.
"""

from __future__ import annotations

import asyncio

from src.config.llm_adapter import LLMAdapter
from src.config.settings import AssociationTreeConfig
from src.embeddings.provider import EmbeddingProvider, cosine_distance
from src.models import AssociationNode, AssociationChain, DOMAINS


SYSTEM_PROMPT = (
    "You are a creative lateral-thinking engine. Your job is to generate "
    "surprising, cross-domain associations that connect seemingly unrelated "
    "concepts. Every association must be a real, defensible concept — not "
    "abstract nonsense. Prefer concrete, specific topics over vague abstractions. "
    f"Available domains: {', '.join(DOMAINS)}"
)

HOP1_TEMPLATE = """Given the topic "{seed_topic}", generate {n} creative lateral associations.

Each association should:
- Connect to the seed topic in a non-obvious way
- Ideally cross into a DIFFERENT domain or field
- Be a real concept, not abstract nonsense
- Be specific (e.g. "termite mound ventilation" not "nature")

Return ONLY a JSON array — no other text:
[{{"topic": "...", "domain": "...", "connection_reason": "..."}}]

Use one of these domains: {domains}"""

HOP_EXPLORING_TEMPLATE = """You are building a chain of creative associations.

The chain so far: {chain_so_far}
Current domain: {current_domain}

From the current topic "{current_topic}", generate {n} lateral associations that:
- Move AWAY from the original seed topic "{seed_topic}" (do NOT circle back)
- Cross into a DIFFERENT domain than "{current_domain}" if possible
- Are surprising but defensible (not random)
- Are specific (e.g. "bioluminescent deep-sea communication" not "ocean life")

Return ONLY a JSON array — no other text:
[{{"topic": "...", "domain": "...", "connection_reason": "..."}}]

Use one of these domains: {domains}"""

HOP_DEEP_TEMPLATE = """You are building a chain of creative associations, now at depth {depth}.

The chain so far: {chain_so_far}
Current domain: {current_domain}

From "{current_topic}", generate up to {n} associations that:
- Are the MOST surprising and specific you can find
- Prefer concrete facts, phenomena, or examples over abstract concepts
- Cross domains if possible
- If you can't find genuinely interesting associations, return fewer than {n}

Return ONLY a JSON array — no other text:
[{{"topic": "...", "domain": "...", "connection_reason": "..."}}]

Use one of these domains: {domains}"""


class AssociationTreeGenerator:
    def __init__(
        self,
        llm: LLMAdapter,
        config: AssociationTreeConfig | None = None,
        embedder: EmbeddingProvider | None = None,
    ):
        self.llm = llm
        self.cfg = config or AssociationTreeConfig()
        self.embedder = embedder
        self._seed_embedding = None

    async def generate_tree(self, seed_topic: str, seed_domain: str = "General") -> list[AssociationChain]:
        """
        Generate a branching association tree from a seed topic.
        Uses depth-first pruning: at each level, keep only the top branches.
        When embeddings are available, pruning rewards chains that travel
        the farthest in semantic space from the seed — silver coins to cancer cure.
        Returns completed chains sorted by preliminary quality.
        """
        root = AssociationNode(
            topic=seed_topic,
            domain=seed_domain,
            connection_reason="seed topic",
            depth=0,
        )

        if self.embedder and self.embedder.is_available:
            root.embedding = await self.embedder.embed(seed_topic)
            self._seed_embedding = root.embedding

        current_leaves = [root]

        for depth in range(1, self.cfg.max_depth + 1):
            if not current_leaves:
                break

            next_leaves: list[AssociationNode] = []
            tasks = [self._expand_node(node, seed_topic, depth) for node in current_leaves]
            results = await asyncio.gather(*tasks, return_exceptions=True)

            for node, children in zip(current_leaves, results):
                if isinstance(children, Exception):
                    print(f"   ⚠️  Error expanding '{node.topic}': {children}")
                    continue
                for child in children:
                    child.parent = node
                    child.depth = depth
                    node.children.append(child)
                    next_leaves.append(child)

            if self.embedder and self.embedder.is_available and next_leaves:
                await self._embed_nodes(next_leaves)

            if depth < self.cfg.max_depth:
                keep = self.cfg.keep_per_level
                ranked = self._rank_for_pruning(next_leaves)
                current_leaves = ranked[:keep]
                pruned = len(ranked) - keep
                if pruned > 0:
                    print(f"   ✂️  Depth {depth}: kept {keep}, pruned {pruned} branches")
            else:
                current_leaves = next_leaves

        completed_chains: list[AssociationChain] = []
        for leaf in current_leaves:
            crossings = leaf.domain_crossings()
            if crossings >= self.cfg.min_domain_crossings:
                chain = AssociationChain(
                    seed_topic=seed_topic,
                    nodes=leaf.chain_to_root(),
                    domain_crossings=crossings,
                )
                chain.total_semantic_distance = self._compute_chain_distance(chain)
                completed_chains.append(chain)

        if not completed_chains and current_leaves:
            best_leaf = max(current_leaves, key=lambda n: n.domain_crossings())
            chain = AssociationChain(
                seed_topic=seed_topic,
                nodes=best_leaf.chain_to_root(),
                domain_crossings=best_leaf.domain_crossings(),
            )
            chain.total_semantic_distance = self._compute_chain_distance(chain)
            completed_chains.append(chain)

        unique = self._deduplicate_chains(completed_chains)
        print(f"\n   🌳 Tree complete: {len(unique)} unique chains generated")
        if self.embedder and self.embedder.is_available:
            print(f"   📐 Embedding cache: {self.embedder.cache_size} vectors")
        return unique

    async def _embed_nodes(self, nodes: list[AssociationNode]) -> None:
        """Batch-embed all nodes that don't have an embedding yet."""
        to_embed = [(i, n) for i, n in enumerate(nodes) if n.embedding is None]
        if not to_embed:
            return
        texts = [n.topic for _, n in to_embed]
        vectors = await self.embedder.embed_batch(texts)
        for (idx, node), vec in zip(to_embed, vectors):
            node.embedding = vec

    def _rank_for_pruning(self, leaves: list[AssociationNode]) -> list[AssociationNode]:
        """Rank leaves for pruning — decides which branches survive.

        With embeddings: uses a composite of semantic distance from seed
        (how far have we traveled?) and domain crossings (structural diversity).
        This rewards the wildest chains — the ones flying farthest from home.

        Without embeddings: falls back to domain crossing count (original behavior).
        """
        has_embeddings = (
            self._seed_embedding is not None
            and any(n.embedding is not None for n in leaves)
        )

        if has_embeddings:
            scored = []
            for node in leaves:
                if node.embedding is not None and self._seed_embedding is not None:
                    dist = cosine_distance(self._seed_embedding, node.embedding)
                else:
                    dist = 0.0
                crossings = node.domain_crossings()
                score = (dist * 0.65) + (crossings / max(node.depth, 1) * 0.35)
                scored.append((node, score))
            scored.sort(key=lambda x: x[1], reverse=True)
            return [n for n, _ in scored]
        else:
            return sorted(leaves, key=lambda n: n.domain_crossings(), reverse=True)

    def _compute_chain_distance(self, chain: AssociationChain) -> float:
        """Compute the real cosine distance from seed to endpoint.
        Falls back to 0.0 if embeddings aren't available."""
        if not chain.nodes:
            return 0.0
        root = chain.nodes[0]
        endpoint = chain.nodes[-1]
        if root.embedding is not None and endpoint.embedding is not None:
            return cosine_distance(root.embedding, endpoint.embedding)
        return 0.0

    async def _expand_node(self, node: AssociationNode, seed_topic: str, depth: int) -> list[AssociationNode]:
        """Generate child associations for a single node."""
        chain_so_far = " → ".join(node.chain_topics())
        domains_str = ", ".join(DOMAINS)
        n = self.cfg.branching_factor

        if depth == 1:
            prompt = HOP1_TEMPLATE.format(
                seed_topic=seed_topic,
                n=n,
                domains=domains_str,
            )
        elif depth <= 4:
            prompt = HOP_EXPLORING_TEMPLATE.format(
                chain_so_far=chain_so_far,
                current_domain=node.domain,
                current_topic=node.topic,
                seed_topic=seed_topic,
                n=n,
                domains=domains_str,
            )
        else:
            prompt = HOP_DEEP_TEMPLATE.format(
                depth=depth,
                chain_so_far=chain_so_far,
                current_domain=node.domain,
                current_topic=node.topic,
                n=n,
                domains=domains_str,
            )

        raw = await self.llm.generate_json(prompt, system=SYSTEM_PROMPT, temperature=0.9)

        children = []
        if isinstance(raw, list):
            for item in raw:
                if isinstance(item, dict) and "topic" in item:
                    children.append(AssociationNode(
                        topic=item["topic"],
                        domain=item.get("domain", "Unknown"),
                        connection_reason=item.get("connection_reason", ""),
                        depth=depth,
                    ))
        return children

    def _deduplicate_chains(self, chains: list[AssociationChain]) -> list[AssociationChain]:
        """Remove chains that share the same endpoint topic."""
        seen_endpoints: set[str] = set()
        unique: list[AssociationChain] = []
        for chain in chains:
            key = chain.endpoint_topic.lower().strip()
            if key not in seen_endpoints:
                seen_endpoints.add(key)
                unique.append(chain)
        return unique
