"""
Association Tree Generator — The Creative Core.

Generates a branching tree of lateral associations from a seed topic,
pruning at each level to keep only the most promising branches.
Each hop is generated by the LLM and aims to cross domain boundaries.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass

from src.config.llm_adapter import LLMAdapter
from src.config.settings import AssociationTreeConfig
from src.models import AssociationNode, AssociationChain, DOMAINS


SYSTEM_PROMPT = (
    "You are a creative lateral-thinking engine. Your job is to generate "
    "surprising, cross-domain associations that connect seemingly unrelated "
    "concepts. Every association must be a real, defensible concept — not "
    "abstract nonsense. Prefer concrete, specific topics over vague abstractions. "
    f"Available domains: {', '.join(DOMAINS)}"
)

HOP1_TEMPLATE = """Given the topic "{seed_topic}", generate {n} creative lateral associations.

Each association should:
- Connect to the seed topic in a non-obvious way
- Ideally cross into a DIFFERENT domain or field
- Be a real concept, not abstract nonsense
- Be specific (e.g. "termite mound ventilation" not "nature")

Return ONLY a JSON array — no other text:
[{{"topic": "...", "domain": "...", "connection_reason": "..."}}]

Use one of these domains: {domains}"""

HOP_EXPLORING_TEMPLATE = """You are building a chain of creative associations.

The chain so far: {chain_so_far}
Current domain: {current_domain}

From the current topic "{current_topic}", generate {n} lateral associations that:
- Move AWAY from the original seed topic "{seed_topic}" (do NOT circle back)
- Cross into a DIFFERENT domain than "{current_domain}" if possible
- Are surprising but defensible (not random)
- Are specific (e.g. "bioluminescent deep-sea communication" not "ocean life")

Return ONLY a JSON array — no other text:
[{{"topic": "...", "domain": "...", "connection_reason": "..."}}]

Use one of these domains: {domains}"""

HOP_DEEP_TEMPLATE = """You are building a chain of creative associations, now at depth {depth}.

The chain so far: {chain_so_far}
Current domain: {current_domain}

From "{current_topic}", generate up to {n} associations that:
- Are the MOST surprising and specific you can find
- Prefer concrete facts, phenomena, or examples over abstract concepts
- Cross domains if possible
- If you can't find genuinely interesting associations, return fewer than {n}

Return ONLY a JSON array — no other text:
[{{"topic": "...", "domain": "...", "connection_reason": "..."}}]

Use one of these domains: {domains}"""


class AssociationTreeGenerator:
    def __init__(self, llm: LLMAdapter, config: AssociationTreeConfig | None = None):
        self.llm = llm
        self.cfg = config or AssociationTreeConfig()

    async def generate_tree(self, seed_topic: str, seed_domain: str = "General") -> list[AssociationChain]:
        """
        Generate a branching association tree from a seed topic.
        Uses depth-first pruning: at each level, keep only the top branches.
        Returns completed chains sorted by preliminary quality.
        """
        root = AssociationNode(
            topic=seed_topic,
            domain=seed_domain,
            connection_reason="seed topic",
            depth=0,
        )

        current_leaves = [root]

        for depth in range(1, self.cfg.max_depth + 1):
            if not current_leaves:
                break

            next_leaves: list[AssociationNode] = []
            tasks = [self._expand_node(node, seed_topic, depth) for node in current_leaves]
            results = await asyncio.gather(*tasks, return_exceptions=True)

            for node, children in zip(current_leaves, results):
                if isinstance(children, Exception):
                    print(f"   ⚠️  Error expanding '{node.topic}': {children}")
                    continue
                for child in children:
                    child.parent = node
                    child.depth = depth
                    node.children.append(child)
                    next_leaves.append(child)

            if depth < self.cfg.max_depth:
                keep = self.cfg.keep_per_level
                ranked = sorted(
                    next_leaves,
                    key=lambda n: n.domain_crossings(),
                    reverse=True,
                )
                current_leaves = ranked[:keep]
                pruned = len(ranked) - keep
                if pruned > 0:
                    print(f"   ✂️  Depth {depth}: kept {keep}, pruned {pruned} branches")
            else:
                current_leaves = next_leaves

        completed_chains: list[AssociationChain] = []
        for leaf in current_leaves:
            crossings = leaf.domain_crossings()
            if crossings >= self.cfg.min_domain_crossings:
                completed_chains.append(AssociationChain(
                    seed_topic=seed_topic,
                    nodes=leaf.chain_to_root(),
                    domain_crossings=crossings,
                ))

        if not completed_chains and current_leaves:
            best_leaf = max(current_leaves, key=lambda n: n.domain_crossings())
            completed_chains.append(AssociationChain(
                seed_topic=seed_topic,
                nodes=best_leaf.chain_to_root(),
                domain_crossings=best_leaf.domain_crossings(),
            ))

        unique = self._deduplicate_chains(completed_chains)
        print(f"\n   🌳 Tree complete: {len(unique)} unique chains generated")
        return unique

    async def _expand_node(self, node: AssociationNode, seed_topic: str, depth: int) -> list[AssociationNode]:
        """Generate child associations for a single node."""
        chain_so_far = " → ".join(node.chain_topics())
        domains_str = ", ".join(DOMAINS)
        n = self.cfg.branching_factor

        if depth == 1:
            prompt = HOP1_TEMPLATE.format(
                seed_topic=seed_topic,
                n=n,
                domains=domains_str,
            )
        elif depth <= 4:
            prompt = HOP_EXPLORING_TEMPLATE.format(
                chain_so_far=chain_so_far,
                current_domain=node.domain,
                current_topic=node.topic,
                seed_topic=seed_topic,
                n=n,
                domains=domains_str,
            )
        else:
            prompt = HOP_DEEP_TEMPLATE.format(
                depth=depth,
                chain_so_far=chain_so_far,
                current_domain=node.domain,
                current_topic=node.topic,
                n=n,
                domains=domains_str,
            )

        raw = await self.llm.generate_json(prompt, system=SYSTEM_PROMPT, temperature=0.9)

        children = []
        if isinstance(raw, list):
            for item in raw:
                if isinstance(item, dict) and "topic" in item:
                    children.append(AssociationNode(
                        topic=item["topic"],
                        domain=item.get("domain", "Unknown"),
                        connection_reason=item.get("connection_reason", ""),
                        depth=depth,
                    ))
        return children

    def _deduplicate_chains(self, chains: list[AssociationChain]) -> list[AssociationChain]:
        """Remove chains that share the same endpoint topic."""
        seen_endpoints: set[str] = set()
        unique: list[AssociationChain] = []
        for chain in chains:
            key = chain.endpoint_topic.lower().strip()
            if key not in seen_endpoints:
                seen_endpoints.add(key)
                unique.append(chain)
        return unique
